# Generated by Django 4.1.4 on 2023-04-24 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0024_teams_team_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arg_backend.players')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
